<?php
session_start();
require_once '../connection/connections.php';
require_once '../vendor/autoload.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: index.php");
    exit();
}

try {
    // Get current timestamp in Philippines timezone
    date_default_timezone_set('Asia/Manila');
    $currentDateTime = date('F d, Y h:i:s A');

    $query = "SELECT p.*, c.category_name 
              FROM products p 
              LEFT JOIN categories c ON p.category_id = c.id 
              ORDER BY p.id ASC";
    $stmt = $pdo->prepare($query);
    $stmt->execute();
    $products = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('ArtMore Admin');
    $pdf->SetTitle('ArtMore Products Report');

    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);

    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

    // Adjusted margins
    $pdf->SetMargins(7, 15, 7);

    $pdf->SetAutoPageBreak(TRUE, 15);
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

    $pdf->AddPage('L');

    // Create the header
    $pdf->SetFont('helvetica', 'B', 20);
    $pdf->Cell(0, 15, 'ArtMore Products Report', 0, 1, 'C');
    $pdf->SetFont('helvetica', '', 10);
    $pdf->Cell(0, 10, 'Generated on: ' . $currentDateTime, 0, 1, 'C');
    $pdf->Ln(10);

    // Table header
    $header = array('#', 'Product Title', 'Category', 'Stock', 'Buying Price', 'Selling Price', 'Added Date');
    
    $pdf->SetFillColor(117, 6, 5);
    $pdf->SetTextColor(248, 184, 60);
    $pdf->SetLineWidth(0.3);
    $pdf->SetFont('helvetica', 'B', 10);

    // Adjusted column widths
    $w = array(20, 65, 45, 25, 40, 40, 35);
    
    // Header
    for($i = 0; $i < count($header); $i++) {
        $pdf->Cell($w[$i], 7, $header[$i], 1, 0, 'C', true);
    }
    $pdf->Ln();

    $pdf->SetFillColor(224, 235, 255);
    $pdf->SetTextColor(0);
    $pdf->SetFont('helvetica', '', 9);

    $fill = false;
    foreach($products as $i => $row) {
        if($pdf->GetY() > $pdf->GetPageHeight() - 20) {
            $pdf->AddPage('L');
            $pdf->SetFillColor(117, 6, 5);
            $pdf->SetTextColor(248, 184, 60);
            $pdf->SetFont('helvetica', 'B', 10);
            for($j = 0; $j < count($header); $j++) {
                $pdf->Cell($w[$j], 7, $header[$j], 1, 0, 'C', true);
            }
            $pdf->Ln();
            $pdf->SetFillColor(224, 235, 255);
            $pdf->SetTextColor(0);
            $pdf->SetFont('helvetica', '', 9);
        }

        $pdf->Cell($w[0], 6, $i + 1, 1, 0, 'C', $fill);
        
        // Adjust text length limits for the new width
        $productTitle = strlen($row['product_title']) > 32 ? 
                       substr($row['product_title'], 0, 29) . '...' : 
                       $row['product_title'];
        $category = strlen($row['category_name']) > 20 ? 
                   substr($row['category_name'], 0, 17) . '...' : 
                   ($row['category_name'] ?? 'No Category');

        $pdf->Cell($w[1], 6, $productTitle, 1, 0, 'L', $fill);
        $pdf->Cell($w[2], 6, $category, 1, 0, 'L', $fill);
        $pdf->Cell($w[3], 6, $row['quantity'], 1, 0, 'C', $fill);
        $pdf->Cell($w[4], 6, 'PHP ' . number_format($row['buying_price'], 2), 1, 0, 'R', $fill);
        $pdf->Cell($w[5], 6, 'PHP ' . number_format($row['selling_price'], 2), 1, 0, 'R', $fill);
        $pdf->Cell($w[6], 6, date('Y-m-d', strtotime($row['created_at'])), 1, 0, 'C', $fill);
        $pdf->Ln();
        $fill = !$fill;
    }

    $pdf->Ln(15);
    $pdf->SetFont('helvetica', 'I', 8);
    $pdf->Cell(0, 10, 'This report was automatically generated by ArtMore Inventory System.', 0, 1, 'C');
    $pdf->Cell(0, 10, 'Page ' . $pdf->getAliasNumPage() . ' of ' . $pdf->getAliasNbPages(), 0, 0, 'C');

    $pdf->Output('ArtMore_Products_Report.pdf', 'D');

} catch(Exception $e) {
    error_log("PDF Generation Error: " . $e->getMessage());
    header("Location: manageProducts.php?error=export_failed");
    exit();
}
?> 